apiVersion: ENC[AES256_GCM,data:OKg=,iv:jAmPfMeMSmWHtPBnvYc4z+ULVCJ+VAI0nYfOee7M0Ic=,tag:Obng+Cp5Th2ovqhSmi9Giw==,type:str]
kind: ENC[AES256_GCM,data:bXIq9e27,iv:hzFhUCYNJRmFy2qsWa/1andT1FYiigCwn6btE7uq9KU=,tag:KaQf7dM40jvhnZY1zPbCtQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xGdE4/VonKSooYVv/HR7OJDa,iv:Ckk+bXn/DlciwwTfqp0PIBhckXGyGJ0Tl9qnhtOZtt0=,tag:AkKp7CuKq7o4A5TD92LI0A==,type:str]
    namespace: ENC[AES256_GCM,data:8UBH,iv:+kIXQnw2D+kUe/6Obo1yQrCLi3e35jZHIac72WKTsnI=,tag:ww3tT6AX+9QznHatBhLz6g==,type:str]
type: ENC[AES256_GCM,data:WQAkjQjw,iv:S8z4feC0yfIRx6I4a7zdj+0jpEM9iewRtt0BdcNuK/8=,tag:0PT+0gLBuZ9NA0Z2ess1Iw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:/pqHFB72oNk91tx5VAdC3G3/FP2BjKh2,iv:GfMAPDJbJRYQint9OQsh9Dn1Mi5WZlTGiY1z3g4pjfU=,tag:VXvZP4TAAk8TtB9TfyUSaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVVYvdC94bkhyM08yWG5V
            b3FyYVpzRTh1Y09UUml0a2lVRUozTGR2QXdZCk9rOEdIT09GMEwxTkxmTWpnTmVu
            YjFEVExxZkp0TlFGN0ZQYi82bTdETVEKLS0tIEFYTDJ6QmFscTdYY1pyS3RacGJl
            LzU0RW5PNkRWVklQWDVBZjZScFdQSUEK5emWcTCvazAU8myqrjiIbQJqaXu6VKaR
            qICj6x90PNS3vrNwAxhTId96FaOtox3CoKCSn9h1/nyBfGXGhzReNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r6y7am38u759z2ktg2zhmn5j8vpvzseptvflaxa69l6wadxlraes806g2h
    lastmodified: "2026-09-12T05:13:39Z"
    mac: ENC[AES256_GCM,data:Z+q/UBT6wcLdO4luvgy/jH0coyoSEsFSNWp7DGj8BcuK9jG2o/f8Y2UQaZBB9AIhzEvlEwmePkGDPcZoCa6cW2GOqtpXg0HICuG/cV0s6ZTz4/jRrArG2tsglDbH9fNiek445rflwDM5wL54zbLDwbRBjFQYc3CkmKaJYu26v2c=,iv:IFQs//xXrQsv48LT8cX15SNGDof2438UdHwMc3qBNis=,tag:docIr+nDzLse0pkiAO5oIw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
