#!/usr/bin/env python3
"""Ensure a file holds a generated secret for every requested key.

Terraform cannot set Proxmox passwords: /access/password rejects API tokens and
demands a ticket. Generating them by hand would put a manual step back into the
build, so the generation lives here.

Existing values are never regenerated, so re-running does not lock anyone out.

With --plaintext the file is written as-is and left out of Git by the caller.
Without it the file is encrypted with SOPS after writing.
"""
import argparse
import json
import secrets
import string
import subprocess
import sys
from pathlib import Path

ALPHABET = string.ascii_letters + string.digits
ROOT = Path(__file__).resolve().parents[1]


def sops(*args, **kwargs):
    return subprocess.run(['sops', *args], check=True, text=True,
                          capture_output=True, cwd=ROOT, **kwargs)


def read(path, plaintext):
    target = ROOT / path
    if not target.exists():
        return {}
    if not plaintext:
        return json.loads(sops('--decrypt', '--output-type', 'json', path).stdout)
    values = {}
    for line in target.read_text(encoding='utf-8').splitlines():
        if ':' not in line or line.lstrip().startswith('#'):
            continue
        key, value = line.split(':', 1)
        values[key.strip()] = value.strip()
    return values


def write(path, values, header, plaintext):
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    body = header + '\n' + '\n'.join(f'{k}: {v}' for k, v in sorted(values.items())) + '\n'
    target.write_text(body, encoding='utf-8')
    if plaintext:
        # Readable by the owner only. Keeping it out of Git is the caller's job.
        target.chmod(0o600)
        return
    try:
        sops('--encrypt', '--in-place', path)
    except subprocess.CalledProcessError:
        # Never leave a plaintext secret behind when encryption was requested.
        target.unlink(missing_ok=True)
        raise


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--file', required=True,
                        help='Target file, relative to the repository root')
    parser.add_argument('--key', action='append', required=True, dest='keys',
                        help='Key that must hold a secret. Repeatable.')
    parser.add_argument('--length', type=int, default=24)
    parser.add_argument('--plaintext', action='store_true',
                        help='Write the file as-is instead of encrypting it with SOPS.')
    parser.add_argument('--header',
                        default='# Generated by tools/ensure-secrets.py. Values are never regenerated.')
    args = parser.parse_args()

    values = read(args.file, args.plaintext)
    added = [key for key in args.keys if not values.get(key)]
    for key in added:
        values[key] = ''.join(secrets.choice(ALPHABET) for _ in range(args.length))
    if added:
        write(args.file, values, args.header, args.plaintext)
        print(f'CHANGED: generated {len(added)} secret(s) in {args.file}')
    else:
        print(f'OK: {args.file} already holds every requested secret')
    return 0


if __name__ == '__main__':
    sys.exit(main())
