#!/usr/bin/env python3
"""Ensure a SOPS file holds a generated secret for every requested key.

Terraform cannot set Proxmox passwords: /access/password rejects API tokens and
demands a ticket. Generating them by hand would put a manual step back into the
build, so the generation lives here and the values stay encrypted at rest.

Existing values are never regenerated, so re-running does not lock anyone out.
"""
import argparse
import json
import secrets
import string
import subprocess
import sys
from pathlib import Path

ALPHABET = string.ascii_letters + string.digits
ROOT = Path(__file__).resolve().parents[1]


def sops(*args, **kwargs):
    return subprocess.run(['sops', *args], check=True, text=True,
                          capture_output=True, cwd=ROOT, **kwargs)


def read(path):
    if not (ROOT / path).exists():
        return {}
    return json.loads(sops('--decrypt', '--output-type', 'json', path).stdout)


def write(path, values, header):
    target = ROOT / path
    body = header + '\n' + '\n'.join(f'{k}: {v}' for k, v in sorted(values.items())) + '\n'
    target.write_text(body, encoding='utf-8')
    try:
        sops('--encrypt', '--in-place', path)
    except subprocess.CalledProcessError:
        # Never leave a plaintext secret behind when encryption fails.
        target.unlink(missing_ok=True)
        raise


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--file', required=True,
                        help='SOPS file, relative to the repository root')
    parser.add_argument('--key', action='append', required=True, dest='keys',
                        help='Key that must hold a secret. Repeatable.')
    parser.add_argument('--length', type=int, default=24)
    parser.add_argument('--header', default='# Generated by tools/ensure-secrets.py. Values are never regenerated.')
    args = parser.parse_args()

    values = read(args.file)
    added = [key for key in args.keys if not values.get(key)]
    for key in added:
        values[key] = ''.join(secrets.choice(ALPHABET) for _ in range(args.length))
    if added:
        write(args.file, values, args.header)
        print(f'CHANGED: generated {len(added)} secret(s) in {args.file}')
    else:
        print(f'OK: {args.file} already holds every requested secret')
    return 0


if __name__ == '__main__':
    sys.exit(main())
