---
- name: Restart timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: true

- name: Reload sshd
  ansible.builtin.systemd:
    name: ssh
    state: reloaded
    enabled: true

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true

- name: Restart sslh
  ansible.builtin.systemd:
    name: sslh
    state: restarted
    enabled: true
